# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Naseer Muhammad"
title_separator: "-"
name: "Naseer Muhammad"
description: "Physicist | Quantum Systems | Quantum Optics | Quantum Computing"
url: "https://naseer-muhammad.github.io"
baseurl: ""  # leave empty if site is at username.github.io
repository: "academicpages/academicpages.github.io"

# Author
author:
  avatar: "speech.png"
  name: "Naseer Muhammad"
  bio: "PhD candidate in the field of Quantum Systems"
  location: "Islamabad, Pakistan"
  employer: "Universitas Indonesia"
  email: "muhammad.naseer@office.ui.ac.id"
  github: "naseer-muhammad"
  instagram: "naseerk00"
  linkedin: "naseer-muhammad-62a0a4190"
  twitter: "NaseerM01681659"

# Publications
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
breadcrumbs: false
words_per_minute: 160
read_more: "disabled"
future: true

# Markdown & SCSS
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Permalinks (important!)
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
